name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      with:
        python-version: "3.11"
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install
    - name: Format
      run: make format
    - name: Test
      run: make test

