name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install
    - name: Format
      run: make format
    - name: Test
      run: make test

